---
deployment:
      tasks:
        - export DEPLOYPATH=/home/skcrafts/public_html  # Add /<app_folder> if required
        - /bin cp * $DEPLOYPATH                           #copy all from root 
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        